import { apiGet } from '../lib/api';
import { esc, fmtDate, fmtPeso } from '../lib/helpers';
import { loadView } from '../lib/router';

let deliveryPage = 1;
let deliveryStatus = 'all';
let deliverySearch = '';
const PAGE_SIZE = 15;

export async function renderDeliveries(): Promise<string> {
  const result = await apiGet<any>(`/invoices/deliveries?page=${deliveryPage}&pageSize=${PAGE_SIZE}&status=${deliveryStatus}&search=${encodeURIComponent(deliverySearch)}`);
  const rows = result.data || [];
  const summary = result.summary || { assigned: 0, unassigned: 0 };
  return `<div class="page-header"><div><h2>Deliveries</h2><p class="page-subtitle">Assign and manage delivery persons for sales.</p></div></div>
    <div class="dashboard-grid report-metrics report-metrics-3"><div class="dashboard-card card-info"><div class="card-label">Assigned deliveries</div><div class="card-value">${summary.assigned}</div><div class="card-sub">Sales with a delivery person</div></div><div class="dashboard-card card-warning"><div class="card-label">Needs assignment</div><div class="card-value">${summary.unassigned}</div><div class="card-sub">Sales without a delivery person</div></div><div class="dashboard-card card-success"><div class="card-label">Showing</div><div class="card-value">${rows.length}</div><div class="card-sub">On this page</div></div></div>
    <div class="dashboard-card deliveries-toolbar"><input id="deliveries-search" type="search" placeholder="Search invoice or buyer..." value="${esc(deliverySearch)}" onkeydown="if(event.key==='Enter')filterDeliveries()" /><select id="deliveries-status" onchange="filterDeliveries()"><option value="all" ${deliveryStatus === 'all' ? 'selected' : ''}>All sales</option><option value="assigned" ${deliveryStatus === 'assigned' ? 'selected' : ''}>Assigned deliveries</option><option value="unassigned" ${deliveryStatus === 'unassigned' ? 'selected' : ''}>Needs assignment</option></select><button class="btn btn-primary" onclick="filterDeliveries()">Search</button></div>
    <div class="dashboard-card deliveries-card"><div class="section-heading"><div><h3>Delivery assignments</h3><p class="card-sub">Assign a delivery person after the sale when delivery details are confirmed.</p></div></div><div class="table-wrap"><table><thead><tr><th>Invoice</th><th>Buyer</th><th>Sale Date</th><th>Current Total</th><th>Status</th><th>Delivery Person</th><th class="actions">Actions</th></tr></thead><tbody>${rows.length ? rows.map((row: any) => `<tr><td data-label="Invoice" style="font-weight:600">${esc(row.invoice_number)}</td><td data-label="Buyer">${esc(row.customer_name)}</td><td data-label="Sale Date">${fmtDate(row.issued_date)}</td><td data-label="Current Total" class="money">${fmtPeso(row.adjusted_total ?? row.total)}</td><td data-label="Status"><span class="status-badge ${row.status}">${esc(row.status)}</span></td><td data-label="Delivery Person"><strong>${esc(row.delivery_person || 'Not assigned')}</strong></td><td data-label="" class="actions"><button class="btn btn-success btn-sm" onclick="showDeliveryModal('${row.id}')">${row.delivery_person ? 'Edit' : 'Assign'}</button><button class="btn btn-sm" onclick="showInvoiceDetail('${row.id}')">View Sale</button></td></tr>`).join('') : '<tr><td colspan="7" class="empty-state">No sales match this delivery filter.</td></tr>'}</tbody></table></div>${result.total > PAGE_SIZE ? `<div class="pagination"><span>Showing ${(deliveryPage - 1) * PAGE_SIZE + 1}–${Math.min(deliveryPage * PAGE_SIZE, result.total)} of ${result.total}</span><button class="btn btn-sm" ${deliveryPage === 1 ? 'disabled' : ''} onclick="changeDeliveryPage(${deliveryPage - 1})">Previous</button><strong>Page ${deliveryPage} of ${result.totalPages}</strong><button class="btn btn-sm" ${deliveryPage >= result.totalPages ? 'disabled' : ''} onclick="changeDeliveryPage(${deliveryPage + 1})">Next</button></div>` : ''}</div>`;
}

export function filterDeliveries() { deliverySearch = (document.getElementById('deliveries-search') as HTMLInputElement)?.value.trim() || ''; deliveryStatus = (document.getElementById('deliveries-status') as HTMLSelectElement)?.value || 'all'; deliveryPage = 1; loadView('deliveries'); }
export function changeDeliveryPage(page: number) { deliveryPage = Math.max(1, page); loadView('deliveries'); }
