import { apiGet } from '../lib/api';
import { esc, fmtDate, fmtPeso } from '../lib/helpers';

let receivablePage = 1;
const RECEIVABLE_PAGE_SIZE = 15;
let receivableSearch = '';
let receivableStatus = 'all';

export async function renderReceivables(): Promise<string> {
  const result = await apiGet<any>(`/invoices/receivables?page=${receivablePage}&pageSize=${RECEIVABLE_PAGE_SIZE}&status=${receivableStatus}&search=${encodeURIComponent(receivableSearch)}`);
  const rows = result.data || [];
  const total = Number(result.total || 0);
  return `<div class="page-header"><div><div class="page-kicker">Credit sales</div><h2>Receivables</h2><p class="page-subtitle">Track unpaid and partially paid credit sales in one place.</p></div></div>
    <div class="receivables-toolbar dashboard-card"><input id="receivables-search" type="search" value="${esc(receivableSearch)}" placeholder="Search buyer or invoice number" onkeydown="if(event.key==='Enter')filterReceivables()" /><select id="receivables-status" onchange="filterReceivables()"><option value="all" ${receivableStatus === 'all' ? 'selected' : ''}>All credit sales</option><option value="unpaid" ${receivableStatus === 'unpaid' ? 'selected' : ''}>Unpaid</option><option value="partial" ${receivableStatus === 'partial' ? 'selected' : ''}>Partially paid</option><option value="paid" ${receivableStatus === 'paid' ? 'selected' : ''}>Paid</option></select><button class="btn btn-primary" onclick="filterReceivables()">Search</button></div>
    <div class="dashboard-card receivables-card"><div class="section-heading"><div><h3>Credit account ledger</h3><p class="card-sub">${total} recorded credit sale${total === 1 ? '' : 's'}</p></div></div><div class="table-wrap"><table><thead><tr><th>Buyer / Charge To</th><th>Invoice</th><th>Sale Date</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th><th class="actions">Action</th></tr></thead><tbody>${rows.length ? rows.map((row: any) => { const balance = Number(row.balance || 0); const paid = Number(row.net_paid || 0); const status = balance <= 0.005 ? 'paid' : paid > 0 ? 'partial' : 'pending'; return `<tr><td data-label="Buyer"><strong>${esc(row.account_name)}</strong></td><td data-label="Invoice">${esc(row.invoice_number)}</td><td data-label="Sale Date">${fmtDate(row.issued_date)}</td><td data-label="Total" class="money">${fmtPeso(row.total)}</td><td data-label="Paid" class="money positive">${fmtPeso(paid)}</td><td data-label="Balance" class="money ${balance > 0 ? 'negative' : 'positive'}">${fmtPeso(Math.max(0, balance))}</td><td data-label="Status"><span class="status-badge ${status}">${status === 'paid' ? 'Paid' : status === 'partial' ? 'Partially paid' : 'Unpaid'}</span></td><td data-label="" class="actions"><button class="btn btn-success btn-sm" onclick="showInvoiceDetail('${row.id}')">${balance > 0.005 ? 'Record Payment' : 'View'}</button></td></tr>`; }).join('') : '<tr><td colspan="8" class="empty-state">No credit sales match this filter.</td></tr>'}</tbody></table></div>${total > RECEIVABLE_PAGE_SIZE ? `<div class="pagination"><span>Showing ${(receivablePage - 1) * RECEIVABLE_PAGE_SIZE + 1}–${Math.min(receivablePage * RECEIVABLE_PAGE_SIZE, total)} of ${total}</span><button class="btn btn-sm" ${receivablePage === 1 ? 'disabled' : ''} onclick="changeReceivablePage(${receivablePage - 1})">Previous</button><strong>Page ${receivablePage} of ${Math.ceil(total / RECEIVABLE_PAGE_SIZE)}</strong><button class="btn btn-sm" ${receivablePage >= Math.ceil(total / RECEIVABLE_PAGE_SIZE) ? 'disabled' : ''} onclick="changeReceivablePage(${receivablePage + 1})">Next</button></div>` : ''}</div>`;
}

export function filterReceivables() { receivableSearch = (document.getElementById('receivables-search') as HTMLInputElement)?.value.trim() || ''; receivableStatus = (document.getElementById('receivables-status') as HTMLSelectElement)?.value || 'all'; receivablePage = 1; (window as any).loadView('receivables'); }
export function changeReceivablePage(page: number) { receivablePage = Math.max(1, page); (window as any).loadView('receivables'); }
